### ISSUE TITLE
Provision forwarding vagrant machines port

### ISSUE THREAD

**Issue by navidshaikh** [bexelbie/vagrant-adbinfo#10]
User story: I am an ADB user, I deployed an atomicapp application inside ADB, now I want to test out if my application is configured properly. I want a way to access the application from host machine (forwarded) port.

This is usually the case with web applications. The user may not want to update the Vagrantfile for forwarded ports every time an app has to be tested. There should some better way to handle this. May be via some plugin ?

Issue is reported at https://github.com/projectatomic/adb-atomic-developer-bundle/issues/87

Should this be a feature of `vagrant-adbinfo`?

**Comment by bexelbie** [comment]
A quick bit of googling leads me to believe that this isn't possible.  It seems your choices are to update the vagrantfile and then `vagrant reload` (which may actually reboot the VM) or to update the port forwarding inside of your VM provider manually.

**Comment by navidshaikh** [comment]
I think reboot should not be a problem. Need to investigate if we can forward the ports w/ updating Vagrantfile, although in either case we need to update the Vagrantfile to match 
desired_state = actual_state of ports.

**Comment by navidshaikh** [comment]
related to https://github.com/bexelbie/vagrant-adbinfo/issues/11

**Comment by bexelbie** [comment]
@navidshaikh I suggest we close this as we have shifted the default in the ADB to be private networking and not port forwarding.

**Comment by navidshaikh** [comment]
@bexelbie : alright.
