### ISSUE TITLE
Support direct exporting of env variables

### ISSUE THREAD

**Issue by strzibny** [bexelbie/vagrant-adbinfo#13]
I would like to see an option to directly export what `vagrant adbinfo` prints.

e.g. by running `vagrant adbinfo export`

**Comment by bexelbie** [comment]
is something like:

$ eval "$(vagrant adb-info)"

acceptable?

**Comment by strzibny** [comment]
> $ eval "$(vagrant adb-info)"

I don't really find it user-friendly, or do you? Of course I know I can always source/eval scripts.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#26
