### ISSUE TITLE
Support SCP in OpenSSH from Cygwin on Windows

### ISSUE THREAD

**Issue by kenfinnigan** [bexelbie/vagrant-adbinfo#20]

**Comment by hferentschik** [comment]
@bexelbie is this still an issue. Why would adbinfo need scp to begin with?

**Comment by hferentschik** [comment]
Can we add label focus:devex as well? Any chance I can get access to the repo btw?

**Comment by bexelbie** [comment]
scp is used to copy items from the box to the host. I believe we can replace it with ruby code, but until that happens we need it.

**Comment by hferentschik** [comment]
> scp is used to copy items from the box to the host. I

Got you. We figured this out as well ;-)

>  I believe we can replace it with ruby code, but until that happens we need it. 

The problems is less with _scp_ per se, but the use of _pscp_ which is binary provided by PuTTY. On Windows where no Cygwin is installed, people might use PuTTY to get _ssh_/_scp_, but with Cygwin installed _scp_ is available as well. Using _pscp_ on Windows forces us to install yet another dependency. 

Really the code should just check whether _scp_ is available independent of the OS. If there is not and we are on Windows one can optionally also try _pscp_. 

Or would _scp_ not be available anyways in a Vagrant install? Maybe there is no need to check for _pscp_ at all.

**Comment by rct** [comment]
Another issue with using pscp: host key error when switching vagrant boxes:

```
$ vagrant adbinfo
WARNING - POTENTIAL SECURITY BREACH!
The server's host key does not match the one PuTTY has
cached in the registry. This means that either the
server administrator has changed the host key, or you
have actually connected to another computer pretending
to be the server.
The new rsa2 key fingerprint is:
ssh-rsa 2048 c6:f6:50:0a:29:17:61:2c:e3:70:dc:68:99:ba:69:76
If you were expecting this change and trust the new key,
enter "y" to update PuTTY's cache and continue connecting.
If you want to carry on connecting but without updating
the cache, enter "n".
If you want to abandon the connection completely, press
Return to cancel. Pressing Return is the ONLY guaranteed
safe choice.
Update cached key? (y/n, Return cancels connection)
```

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#25
