### ISSUE TITLE
Add command for exporting sample Vagrantfile

### ISSUE THREAD

**Issue by navidshaikh** [bexelbie/vagrant-adbinfo#21]
@veillard suggested to add a command in plugin to export a sample Vagrantfile.

For example:

``` bash
vagrant adbinfo export-vagrantfile
```

can export a sample `Vagranfile` as below in current working directory

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant file for libvirt/kvm and virtualbox provider

Vagrant.configure(2) do |config|
  config.vm.box = "atomicapp/dev"

  config.vm.network "forwarded_port", guest: 2376, host: 2379, auto_correct: true

  config.vm.provider "virtualbox" do |vbox, override|
    vbox.memory = 1024
    vbox.cpus = 2

    # Enable use of more than one virtual CPU in a virtual machine.
    vbox.customize ["modifyvm", :id, "--ioapic", "on"]
  end

end
```

This could be handy for quick starts.

**Comment by bexelbie** [comment]
I like the idea, I am not sold on the sample file as outlined.  How about we choose the sample file once we resolve some of the ip resolution patches?

**Comment by navidshaikh** [comment]
@bexelbie : Yes, the sample file going to be evolved.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#24
