### ISSUE TITLE
Return better error messages

### ISSUE THREAD

**Issue by strzibny** [bexelbie/vagrant-adbinfo#25]
Currently adbinfo plugin expects certain types of guests but it should give the user a nice error message if it can't be used.

See:

```
$ vagrant adbinfo
scp: /home/vagrant/.docker: No such file or directory
The capability 'forwarded_ports' could not be found. This is an internal error
that users should never see. Please report a bug.
```

**Comment by navidshaikh** [comment]
@strzibny :
I can understand the `scp` error, the box does not have required certs directory, however how did you get the following error?

```
The capability 'forwarded_ports' could not be found. This is an internal error
that users should never see. Please report a bug.
```

**Comment by strzibny** [comment]
@navidshaikh if you accidentally run with other boxes...

**Comment by bexelbie** [comment]
@strzibny were you using virtualbox or libvirt?  That error is, I believe, caused when you use a provider that does not support the forwarded_ports capability.  VirtualBox has it, libVirt does not.

I have patches pending (#23, #24) that should eliminate this problem.  However those patches have different problems :)

**Comment by strzibny** [comment]
Yes, `libvirt` provider...

**Comment by bexelbie** [comment]
+1 to close - no longer needed

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#28
