### ISSUE TITLE
adbinfo should also give OpenShift information 

### ISSUE THREAD

**Issue by LalatenduMohanty** [bexelbie/vagrant-adbinfo#26]
If the OpenShift is running in the ADB vagrant box, vagrant-adbinfo should publish the information

Refer: https://github.com/projectatomic/adb-atomic-developer-bundle/issues/110

**Comment by navidshaikh** [comment]
@maxandersen @xcoulon:

What all OpenShift information is needed for clients to connect to it? Is there something specific for Eclipse connection?
Also should the connection information be exported in environment variables?

**Comment by xcoulon** [comment]
adding @fbricon and @adietish  and @jcantrill as they are currently working on the OpenShift tooling

**Comment by jcantrill** [comment]
@navidshaikh  Not exactly sure what you question is, but to connect to an OpenShift cluster, it requires the connection url and an oauth token

**Comment by maxandersen** [comment]
basic info like the url needed for oc and eclipse tools.

i.e. OPENSHIFT_URL=https://openshift.10.0.0.1.xip.io:8443

**Comment by LalatenduMohanty** [comment]
Can someone add "focus:devex" Label to the issue

**Comment by praveenkumar** [comment]
@navidshaikh Currently ADB OpenShift vagrant files have hardcoded private IP [0] and that can be used to provide relative information for OpenShift.

OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

[0] https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-with-openshift/Vagrantfile#L12

**Comment by bexelbie** [comment]
@praveenkumar @praveenkumar is there a command we can run, like 'oc status' that would tell us the ip in case the user changed it?

**Comment by hferentschik** [comment]
I think the way to go is via the OpenShift master config. In our case that's `/var/lib/origin/openshift.local.config/master/master-config.yaml`. The config contains two keys `masterPublicURL` and `publicURL` which is exactly what we need. 

Depending on how OpenShift is setup on the VM (atm we use Vagrant provisioning, but it should beome a service on the actual VM) and when it starts, the config files might not exist. So adbinfo needs to take this into account as well and reflect this in the output (eg "OpenShift not started yet" or something along this line).

**Comment by hferentschik** [comment]
> Also should the connection information be exported in environment variables?

I don't think this is required

**Comment by bexelbie** [comment]
@hferentschik @hferentschik Would it be enough to use what is in the file and omit output if no file exists? I don't want to tell someone OpenShift isn't started when they never wanted it.

**Comment by hferentschik** [comment]
> Would it be enough to use what is in the file and omit output if no file exists? 

Sure. Sounds reasonable. Just wanted to make sure that the case of the config file not existing must be handled as well.

**Comment by bexelbie** [comment]
@hferentschik if we don't export the connection information as environment variables, how are you wanting to pass it to Eclipse?  

I was under the impression you wanted the standard DOCKER\* env vars and something like this:

OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

Does this work?  If not, what do you want us to provide, exactly?

**Comment by maxandersen** [comment]
we can start with OPENSHIFT_URL and we'll derive the console from that.

The contents of the variable should just be what the cli (and indirectly eclipse) will accept as the connection string. Thus https://10.1.2.2:8443 should be fine.

**Comment by hferentschik** [comment]
> if we don't export the connection information as environment variables, how are you wanting to pass it to Eclipse? 

I am not sure whether Eclipse itself would call the eval adbinfo. In fact I don't think it does. The setting of the environment variables are mainly for command line use of Docker. I guess we can export `OPENSHIFT_URL` as well.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#23
