### ISSUE TITLE
Determination of the DOCKER_HOST is too simplistic

### ISSUE THREAD

**Issue by hferentschik** [bexelbie/vagrant-adbinfo#33]
At the moment the value of _DOCKER_HOST_ reported by adbinfo is fixed to 127.0.0.1. The host should be determined by the configured public IP. The Docker daemon should be accessible via this IP and also containers and their exposed ports.

The detection of the the Docker port via checking for a port forward in the Vagrant config seems wrong as well. Provided we use the private network IP to access the Docker daemon we can just use the default port.

**Comment by bexelbie** [comment]
You are correct.  The latest code fixes this.  Please try it and let us know if it is working for you and if we can close this issue.

**Comment by hferentschik** [comment]
> The latest code fixes this. Please try it and let us know if it is working for you and if we can close this issue.

Testing ...

I am also having some issues with TLS, but that is unrelated I think.

**Comment by hferentschik** [comment]
Ok, as of 0.0.6 the host IP is correct.

**Comment by bexelbie** [comment]
@hferentschik Can you elaborate on the TLS issue?

**Comment by hferentschik** [comment]
I have to disable TLS verification due to 

```
An error occurred trying to connect: Get https://10.1.2.2:2376/v1.20/containers/json: x509: certificate is valid for 127.0.0.1, not 10.1.2.2
```

As far as I understand this will be fixed by https://github.com/projectatomic/adb-atomic-developer-bundle/pull/127

On a different note, if I disable tls verfication, _adbinfo_ still reports DOCKER_CERT_PATH and DOCKER_TLS_VERIFY. Really in this case they should not be set. I have to manually unset them.
