### ISSUE TITLE
plugin should run automatically when adb is started

### ISSUE THREAD

**Issue by bexelbie** [bexelbie/vagrant-adbinfo#34]
Plugin should run automatically when the ADB is started like https://github.com/projectatomic/adb-vagrant-registration/tree/master/lib/vagrant-registration

@strzibny can you provide any guidance?

**Comment by bexelbie** [comment]
@LalatenduMohanty how does the prompting for registration for the RHEL CDK work? could we adapt that?

**Comment by strzibny** [comment]
@bexelbie What would be the use case? You want automatic way of exposing the env variables or? Something I suggested here https://github.com/projectatomic/vagrant-adbinfo/issues/13 but as part of vagrant up process or?

Of course technically speaking I can help.

**Comment by LalatenduMohanty** [comment]
@bexelbie RHEL CDK expect the user to install the plugin. I does not happen automatically. I think we need to sync with the team which is working on a installer for CDK.

**Comment by bexelbie** [comment]
@strzibny @strizbny I'd like to see vagrant adbinfo run automatically after vagrant up. It seems that vagrant register is called automatically as part of vagrant up, somehow. 

Re #13 can you provide some advice in the best way to export those variables automatically from Python? My foo there is not as strong as it should be or I need more coffee and sleep.

**Comment by bexelbie** [comment]
@LalatenduMohanty @LalatenduMohanty I meant auto-run after vagrant up, not auto-install.

**Comment by LalatenduMohanty** [comment]
@bexelbie ah, I missed that. Yes, if you have vagrant-registration installed and it is a RHEL guest ,  its asks for username and password for registration every time you do a "vagrant up" . 

I think its good idea to put auto detection (guest capability) code in the plugin. 
e.g  https://github.com/projectatomic/adb-vagrant-registration/blob/master/plugins/guests/redhat/plugin.rb

**Comment by bexelbie** [comment]
@LalatenduMohanty yes, I think having something we can use to detect an ADB would be a huge help.  Can you walk me through the methodology?

**Comment by strzibny** [comment]
@bexelbie so instead of the necessity of running the `vargant adbinfo` command the instructions will get printed after vagrant up (printed or sourced?)? Is that what you are after?

**Comment by navidshaikh** [comment]
@strzibny : There are two actions which are performed on the execution of plugin
1. Re-generation of the TLS certs for docker daemon 
2. Printing the information

We wanted to 1 to happen when the box is up (provisioning step), while the printing of docker daemon information can happen while user execute the plugin.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#21
