### ISSUE TITLE
DOCKER_TLS_VERIFY is always set

### ISSUE THREAD

**Issue by hferentschik** [bexelbie/vagrant-adbinfo#38]
_DOCKER_TLS_VERIFY_ is hard coded to _1_. In case someone changes the Docker daemon settings to disable TLS, _adbinfo_ will not display the correct information. 

The implementation should check the actual Docker configuration (aka whether 'tlsverify' is set) and report _DOCKER_TLS_VERIFY_ accordingly.

**Comment by navidshaikh** [comment]
@hferentschik : Exposing the `docker` daemon over TCP without TLS is unsafe. What use case is targeted for running daemon without TLS?

**Comment by bexelbie** [comment]
I agree that not using TLS is a bad idea, however I think we should actually check for this, if reasonable for completeness.

**Comment by hferentschik** [comment]
> Exposing the docker daemon over TCP without TLS is unsafe. What use case is targeted for running daemon without TLS? 

Not so much a concrete use case, but it is possible. Someone might just want to safe himself the trouble with certificates and change the setting in the VM. Good practice or not, adbinfo will then report a wrong value. It's not so much about whether it makes terribly sense, but about the correctness of the implementation.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#17
