### ISSUE TITLE
don't glob host machines 127.0.0.1:* ports

### ISSUE THREAD

**Issue by navidshaikh** [bexelbie/vagrant-adbinfo#39]
could we make it so adb/cdk would not default to map services into 127.0.0.1 and instead use a specific ip - an ip that even could be dumped out in adbinfo as CDK_HOST or similar.

I would like to reduce the times users need to go via localhost with obscure port values instead of a proper ip/dns + sensible port values.

please note: the 127.0.0.1 here is the users machine host - we should not require that to be used, but rather setup the CDK box to have its own IP.

original issue: https://github.com/projectatomic/adb-atomic-developer-bundle/issues/113

**Comment by navidshaikh** [comment]
Cc @maxandersen

This fix needs certs generation on the boot time of VM, which is addressed by https://github.com/projectatomic/adb-atomic-developer-bundle/pull/127 and support from vagrant-adbinfo plugin https://github.com/projectatomic/vagrant-adbinfo/issues/40, which is part of v0.0.8 release of the plugin.

**Comment by maxandersen** [comment]
Great!

**Comment by navidshaikh** [comment]
Plugin re-generates the certs after the machine boots using the IP assigned to box.
Although there is another issue #55 which is causing the OpenShift containers to be killed because of `docker` daemon restart, but it can be addressed separately.
Closing the issue.
