### ISSUE TITLE
vagrant password hard coded instead of using ssh key

### ISSUE THREAD

**Issue by rctrh** [bexelbie/vagrant-adbinfo#53]
The pscp command line looks like it includes a hard coded password '-pw vagrant' instead of trying to use ssh keys.  I don't know if this is for pscp only or applies to scp as well.

`pscp -r -P 2222 -pw vagrant -p vagrant@127.0.0.1:/home/vagrant/.docker`

**Comment by rct** [comment]
This is related to using Putty's pscp, which doesn't have the same key management options as OpenSSH's scp.  This is related to #20 and #51.   Hopefully if scp is used the ssh keys maintained by vagrant will be used and the hard coded password will be removed.

**Comment by hferentschik** [comment]
Can we add the label focus:devex?

**Comment by hferentschik** [comment]
So this would become an issue, if someone changes its setup from the default vagrant one, right?

**Comment by rct** [comment]
As I understand it, if the user changes the vagrant user password, adbinfo will start to fail without it being clear why.

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#14
