### ISSUE TITLE
Rename Plugin

### ISSUE THREAD

**Issue by bexelbie** [bexelbie/vagrant-adbinfo#54]
@LalatenduMohanty has pushed strongly in conversations with me to rename the plugin.  He would like to see it not contain the word ADB so that it is easier for derived downstream projects/products to use the plugin.

I propose we rename it nandi as it serves as an intermediary between the developer and the development environment.

**Comment by LalatenduMohanty** [comment]
@bexelbie I am fine with anything without adb string in the name.  BTW nandi sounds good :)

**Comment by hferentschik** [comment]
Is this not really a duplicate or at least a tightly relate to #37?

**Comment by hferentschik** [comment]
Nandi!? Either way, the rename should imo happen prior to GA. At the moment the rename is only marked as "nice to have", but given that a rename is quite simple it makes sense to settle for a "proper" name prior to releasing it as part of a GA and then changing it later.

**Comment by bexelbie** [comment]
@hferentschik #37 updated.  also see https://en.wikipedia.org/wiki/Nandi_(bull)
