### ISSUE TITLE
Need documentation about how adbinfo fits in to the overall plan of ADB

### ISSUE THREAD

**Issue by LalatenduMohanty** [bexelbie/vagrant-adbinfo#57]
Need some documentation in the landing page of adbinfo, so that if someone somehow comes to the project, he/she should be able to understand the intent. 

May be put some pointers to https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-the-box-with-host-based-tools-eclipse-and-clis

**Comment by bexelbie** [comment]
Stop opening issues on things I am actively doing right now :)
