### ISSUE TITLE
typo in plugin output

### ISSUE THREAD

**Issue by optak** [bexelbie/vagrant-adbinfo#62]
Output of "vagrant adbinfo" contains typo in recommended command to run:
Output:     # eval "$(vagrant adb-info)"
Expected: # eval "$(vagrant adbinfo)"

**Comment by navidshaikh** [comment]
It was a bug in v0.0.5 release of the plugin and fixed in subsequent release, kindly update the plugin

```
vagrant plugin update vagrant-adbinfo
```

**Comment by optak** [comment]
I tried, both from upstream and from cdk.zip from 11-Dec-2015, but I can't get newer version:
$ vagrant plugin update vagrant-adbinfo
Updating plugins: vagrant-adbinfo. This may take a few minutes...
All plugins are up to date.
$ vagrant plugin list
vagrant-adbinfo (0.0.5)
- Version Constraint: 0.0.5

**Comment by bexelbie** [comment]
@optak was your initial plugin install from the RHEL cdk.zip? Could you try deleting the plugin and reinstalling via vagrant?

**Comment by optak** [comment]
@bexelbie you're right, after removing this plugin, "vagrant plugin install" installs the right version.
I expected "vagrant plugin" command to distinguish plugins based on name and not also source of plugin or any other metadata.

**Comment by bexelbie** [comment]
@optak It was a hunch on my part, however I think it is going to work out well.  Users of the RHEL CDK should be using the latest version distributed by RH.  Upstream users should be using the latest (or their favorite) version.
