### ISSUE TITLE
Repository should have CHANGELOG.md

### ISSUE THREAD

**Issue by brgnepal** [bexelbie/vagrant-adbinfo#66]
Could we have a file(`CHANGELOG.md`) to track the changes between released versions?

A good read on change log <a href="http://keepachangelog.com/" target="_blank">here</a>.

Few examples:
- Short changelog: <a href="https://github.com/ruby/ruby/blob/trunk/ChangeLog" target="_blank">Ruby language's Changelog</a>
- Descriptive changelog: <a href="https://github.com/rails/rails/blob/4-1-stable/activemodel/CHANGELOG.md" target="_blank">Rails framework's Changelog</a>

**Comment by LalatenduMohanty** [comment]
+1, change log is a good idea

**Comment by brgnepal** [comment]
Could we add this in the next release with notable changes in current release and if possible changes from previous releases?

**Comment by bexelbie** [comment]
+1
