### ISSUE TITLE
When complete, the plugin needs to be packaged by distributions

### ISSUE THREAD

**Issue by bexelbie** [bexelbie/vagrant-adbinfo#7]

**Comment by navidshaikh** [comment]
I had a discussion about it with @strzibny and [gem2rpm](https://github.com/fedora-ruby/gem2rpm/graphs/contributors) can be used to package the plugin

```
gem fetch vagrant-adbinfo
gem2rpm vagrant-adbinfo-0.0.3.gem  > vagrant-adbinfo.spec
cp vagrant-adbinfo-0.0.3.gem ~/rpmbuild/SOURCES
rpmbuild -ba vagrant-adbinfo.spec
```

**Comment by strzibny** [comment]
I will document packaging plugins hopefully officially on Fedora wiki.

**Comment by strzibny** [comment]
Here it is: https://fedoraproject.org/wiki/PackagingDrafts/Vagrant

**Comment by navidshaikh** [comment]
@strzibny : Thank you for the Wiki

**Comment by navidshaikh** [comment]
I followed the guide and tried adding a build on copr - the build succeed on f22 however failed for f23 and rawhide.

https://copr.fedoraproject.org/coprs/nshaikh/vagrant-adbinfo/build/139020/

**Comment by strzibny** [comment]
@navidshaikh seems that the build itself succeeded...can you try to resubmit? Otherwise get the Copr guys to see what's wrong.

**Comment by navidshaikh** [comment]
@strzibny : Its failing for EPEL, built for Fedora 22, 23 and rawhide https://copr.fedoraproject.org/coprs/nshaikh/vagrant-adbinfo/build/139978/.

Yet another build with latest code:
https://copr.fedoraproject.org/coprs/nshaikh/vagrant-adbinfo/build/140009/

**Comment by strzibny** [comment]
@navidshaikh Of course it fails for EPEL, there is no Vagrant.

**Comment by navidshaikh** [comment]
@strzibny: Okay.
I will wait for getting it in Fedora to close the issue.
