### ISSUE TITLE
Info log messages should be used when certificates get copied to host

### ISSUE THREAD

**Issue by hferentschik** [bexelbie/vagrant-adbinfo#79]
Currently everything adbinfo does is in silent mode which makes it hard to a user to understand what's even going on. For example it would be nice to get some info logging that client certificate files are getting copied to the host and to where. 

Atm the output of `vagrant adbinfo` needs to also be evaluated by a shell, so this might be hard to do. This is one more reason to make certificate generation and re-configuration of the Docker daemon part of the provisioning. 

Also the README as well as the built-in help should be more descriptive.

**Comment by LalatenduMohanty** [comment]
@hferentschik +1 . As per discussion with @navidshaikh , we will make make certificate generation and re-configuration of the Docker daemon part of provisioning

**Comment by hferentschik** [comment]
> As per discussion with @navidshaikh , we will make make certificate generation and re-configuration of the Docker daemon part of provisioning

Awesome. This will allow to write out some info messages to the user during this provisioning which will help the user to better understand what's going on.

**Comment by hferentschik** [comment]
Could you add label focus:devex ;-)

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#5
