### ISSUE TITLE
Replace `scp ...` call with a subprocess that allows for return code checking

### ISSUE THREAD

**Issue by bexelbie** [bexelbie/vagrant-adbinfo#8]

**Comment by rctrh** [comment]
I commented in issue #51 
"FWIW, one of the gems included with Vagrant is Net-SCP, so in theory you could do something in pure Ruby. I'm not sure if all of the supporting crypto bits are there, though one would assume they must be using it if they are including it."

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#27
