### ISSUE TITLE
Don't use .docker for Docker client certificates 

### ISSUE THREAD

**Issue by hferentschik** [bexelbie/vagrant-adbinfo#80]
Currently the Docker client certificates end up in a hidden directory `.docker`, eg `.vagrant/machines/cdk/virtualbox/.docker/`. It seems odd to have another hidden directory underneath `.vagrant`. Just `docker` would be better.

**Comment by LalatenduMohanty** [comment]
@hferentschik agree. I will send a PR

**Comment by hferentschik** [comment]
Thanks

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#4
