### ISSUE TITLE
On Windows adbinfo might require user interaction

### ISSUE THREAD

**Issue by hferentschik** [bexelbie/vagrant-adbinfo#86]
On Windows a call to `adbinfo` can require manual user interaction. Most likely only in combination with PuTTY:

```
$ vagrant adbinfo
WARNING - POTENTIAL SECURITY BREACH!
The server's host key does not match the one PuTTY has
cached in the registry. This means that either the
server administrator has changed the host key, or you
have actually connected to another computer pretending
to be the server.
The new rsa2 key fingerprint is:
ssh-rsa 2048 f1:c9:d7:16:60:ec:68:93:fb:ee:c7:95:30:0a:66:8d
If you were expecting this change and trust the new key,
enter "y" to update PuTTY's cache and continue connecting.
If you want to carry on connecting but without updating
the cache, enter "n".
If you want to abandon the connection completely, press
Return to cancel. Pressing Return is the ONLY guaranteed
safe choice.
Update cached key? (y/n, Return cancels connection) y
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:

setx DOCKER_HOST tcp://10.1.2.2:2376
setx DOCKER_CERT_PATH C:\DeveloperPlatform\cdk\openshift-vagrant\.    vagrant\machines\cdk\virtualbox\.docker\
setx DOCKER_TLS_VERIFY 1
setx DOCKER_MACHINE_NAME 7a2c9e4
```

This prevents for automated usage of `adbinfo` by tooling. This might be related to #20 and become not relevant if using ssh/scp. But as long as PuTTY is used, one probably needs to add an option which allows the automatic update of the cached key.

**Comment by optak** [comment]
This issue is not related only to putty, I have the same problem with ssh from cygwin.

**Comment by hferentschik** [comment]
Hmm, we need to investigate why this is not an issue on Linux / OS X.

**Comment by navidshaikh** [comment]
> This issue is not related only to putty, I have the same problem with ssh from cygwin.

Presently, plugin does not understand if it is being ran from cygwin, it sees the environment as Windows and uses the password (instead of ssh keys) for copy over ssh.

**Comment by rct** [comment]
This is another symptom using Putty's PSCP.     The openssh managed by vagrant turns off strict host key checking which gets around these issues. 

IMHO, The priority should be removing the dependancy on Putty for windows. 

See #20, #51, #53 

ssh (openssh) is essentially a vagrant requirement and I believe is embedded.  Putty doesn't satisfy that requirement and the only thing introducing a dependency on Putty is adbinfo.

**Comment by optak** [comment]
I discuss this issue with David Kutalek and it seems that this is blocker for CDK-eclipse ingegration, since they don't use terminal at all.

**Comment by hferentschik** [comment]
> it seems that this is blocker

+1

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#2
