### ISSUE TITLE
Add libvirt provider support

### ISSUE THREAD

**Issue by bexelbie** [bexelbie/vagrant-adbinfo#9]
In this case, use the guest IP address and the standard docker port (opposite of existing virtualbox methodology)

**Comment by dkutalek** [comment]
Hi, I probably hit this issue, with this error message:
$ vagrant adbinfo
The capability 'forwarded_ports' could not be found. This is an internal error
that users should never see. Please report a bug.

**Comment by navidshaikh** [comment]
@dkutalek : Which vagrant box you used?

**Comment by navidshaikh** [comment]
@dkutalek : Check Quick Start steps https://github.com/bexelbie/vagrant-adbinfo#quick-start

**Comment by bexelbie** [comment]
@dkutalek This error is specific to the libvirt provider, I believe.  Patches #23 and #24 will fix this when they land.

**Comment by dkutalek** [comment]
@navidshaikh: I used libvirt one, so looking forward to fixes mentioned in comment above. Thanks.
